# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crofty < Formula
  desc "Own your website: a Markdown-to-published-site pipeline"
  homepage "https://crofty.site"
  version "0.10.1"
  license "AGPL-3.0-or-later"

  depends_on "hugo"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ShiroDoromoto/crofty/releases/download/v0.10.1/crofty_0.10.1_darwin_amd64.tar.gz"
      sha256 "75da5f93bb33feebf71e0795fcb4ca2c40b39658f586fd231e45f0a6a30ae2cc"

      define_method(:install) do
        bin.install "crofty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ShiroDoromoto/crofty/releases/download/v0.10.1/crofty_0.10.1_darwin_arm64.tar.gz"
      sha256 "f5a27a9ec6efaffff0e77d8b87a719905ad09f071412e88e447ffee8935a30e6"

      define_method(:install) do
        bin.install "crofty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShiroDoromoto/crofty/releases/download/v0.10.1/crofty_0.10.1_linux_amd64.tar.gz"
      sha256 "b47f5689af3c80f58426bf24db379bb8192fcf3beee07ab6ad51f9e606d1e3ff"
      define_method(:install) do
        bin.install "crofty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShiroDoromoto/crofty/releases/download/v0.10.1/crofty_0.10.1_linux_arm64.tar.gz"
      sha256 "51feb32b3afcc0cdf73834253f1b43c5aaed74e771633c3746be6936bd6f8a85"
      define_method(:install) do
        bin.install "crofty"
      end
    end
  end

  test do
    system bin/"crofty", "version"
  end
end
