# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crofty < Formula
  desc "Own your website: a Markdown-to-published-site pipeline"
  homepage "https://crofty.site"
  version "0.8.1"
  license "AGPL-3.0-or-later"

  depends_on "hugo"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ShiroDoromoto/crofty/releases/download/v0.8.1/crofty_0.8.1_darwin_amd64.tar.gz"
      sha256 "0548d5a26a033503874058e801ec1b27e09f2a87416722fc336169845d9147f3"

      define_method(:install) do
        bin.install "crofty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ShiroDoromoto/crofty/releases/download/v0.8.1/crofty_0.8.1_darwin_arm64.tar.gz"
      sha256 "13b56ffe7fee34e1bfeb4d721a111ac9b32acd17cd03a2617be3f1a7be2d07e0"

      define_method(:install) do
        bin.install "crofty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShiroDoromoto/crofty/releases/download/v0.8.1/crofty_0.8.1_linux_amd64.tar.gz"
      sha256 "c4bb0d7b6a851315de8c59a944dcd0fb07717e0916139dbbb56c60518828edda"
      define_method(:install) do
        bin.install "crofty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ShiroDoromoto/crofty/releases/download/v0.8.1/crofty_0.8.1_linux_arm64.tar.gz"
      sha256 "5b30098e7c67829d5df68849a9c35c3b6e1e1cc462424c228cd6ffb70363deae"
      define_method(:install) do
        bin.install "crofty"
      end
    end
  end

  test do
    system bin/"crofty", "version"
  end
end
